//COURSE
export const FETCH_COURSE = "FETCH_COURSE";
export const FETCH_COURSE_DETAIL = "FETCH_COURSE_DETAIL";
export const FETCH_COURSE_SEARCH = "FETCH_COURSE_SEARCH";

//USER
export const FETCH_LOGIN = "FETCH_LOGIN";

//CATEGORY
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const FETCH_CATEGORY_DETAIL = "FETCH_CATEGORY_DETAIL";

//CART
export const FETCH_ADD_CART = "FETCH_ADD_CART";
export const FETCH_DELETE_CART = "FETCH_DELETE_CART";